fix handling of seconds in the FormDateTimeSelect
laminas/laminas-form pull request #258
Opened 2024-01-04 19:33 UTC by mimmi20

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR wants to fix the handling of seconds in the FormDateTimeSelect. This is related to issue #236.

2024-01-07 22:40 UTC, gsteel requested changes
Thanks @mimmi20 - Just a little bit more verbosity for the test case will better identify test expectations, but other than that LGTM!

2024-01-07 22:40 UTC, gsteel commented on test/View/Helper/FormDateTimeSelectTest.php
> +    public function testGetElementsWithSesonds(): void
```suggestion
    public function testGetElementsWithSeconds(): void
```

2024-01-07 22:40 UTC, gsteel commented on test/View/Helper/FormDateTimeSelectTest.php
> +        self::assertStringContainsString('<select name="day">', $markup);
```suggestion
        self::assertStringContainsString('<select name="hour">', $markup);
        self::assertStringContainsString('<select name="minute">', $markup);
        self::assertStringNotContainsString('<select name="second">', $markup);
```

2024-01-08 09:39 UTC, gsteel approved these changes
Thank you @mimmi20

I'll leave the merge up to you @Slamdunk - This should maybe go into 3.17.1 but I guess there's no point if you'll be releasing 3.18.0 soon.

2024-01-09 08:22 UTC, Slamdunk approved these changes

2024-01-09 08:25 UTC, merged