Improve type inference for FormElementManager::get()
laminas/laminas-form pull request #260
Opened 2024-01-09 12:36 UTC by gsteel

Currently, if you provide `FormElementManager::get()` with a FQCN, it infers `ElementInterface` instead of the given FQCN. This patch fixes that…

There are some un-related psalm issues from recent patches. Let me know if you want these baselined here

2024-01-09 13:05 UTC, Slamdunk approved these changes

2024-01-09 18:06 UTC, Xerkus requested changes
Psalm template constraints are not used in conditional block. See comment

2024-01-09 18:06 UTC, Xerkus commented on src/FormElementManager.php
> +     * @psalm-return ($name is class-string<T> ? T : mixed)
```suggestion
     * @psalm-return ($name is class-string<ElementInterface> ? T : ElementInterface)
```

This does not work as expected. See https://github.com/laminas/laminas-inputfilter/pull/97#discussion_r1446307372 for more context

Also instead of mixed as fallback return `ElementInterface` as form element manager validates return type.

Add regular `@return` annotation for IDEs

2024-01-10 14:51 UTC, Xerkus approved these changes

2024-01-10 14:51 UTC, merged