Helper optional renderer consistency
laminas/laminas-form pull request #266
Opened 2024-02-01 10:57 UTC by oldpec

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Inconsistencies in the way different view helpers load plugins meant that while most helpers worked without a renderer being attached on $this->view, a few failed.

This PR brings the few cases where plugins weren't successfully created when $this->view wasn't populated into line with the others and includes unit tests that fail before the change.

- Are you fixing a BC Break?

Arguably?
In some older versions of PHP (ie 7.4) some of these cases (eg FormSelect::getFormHiddenHelper()) would work (because $this->view being null only became a TypeError for method_exists() in PHP 8.0) and then stopped working on current PHP versions.
So these fixes would make code that worked for people under older versions of PHP continue to work as they uplift their PHP and Laminas versions.

There is a little background on:
https://discourse.laminas.dev/t/laminas-form-view-helper-retrieval-consistency/3591

2024-02-05 09:51 UTC, froschdesign commented on src/View/Helper/FormSelect.php
> +            if ($this->view && method_exists($this->view, 'plugin')) {
For consistency, I suggest an early return as is the case in the other helpers:

```php
if ($this->formHiddenHelper !== null) {
    return $this->formHiddenHelper;
} 
```

2024-02-05 23:30 UTC, oldpec commented on src/View/Helper/FormSelect.php
> +            if ($this->view && method_exists($this->view, 'plugin')) {
I made minimal changes for each but am happy to bring them more into alignment.
will do null first, ie:
`if (null !== $this->formHiddenHelper) {`
as that seems to be what the others do

2024-02-08 08:42 UTC, Slamdunk requested changes
Thank you very much for fixing this bug :muscle: 

Just minor improvements: only booleans should be put in `if` condition, and condition should be as narrow as possible to let unknown bugs emerge as soon as possible.

Then we can :ship: it

2024-02-08 08:42 UTC, Slamdunk commented on src/View/Helper/AbstractFormDateSelect.php
> +        if ($this->view && method_exists($this->view, 'plugin')) {
```suggestion
        if (null !== $this->view && method_exists($this->view, 'plugin')) {
```

2024-02-08 08:42 UTC, Slamdunk commented on src/View/Helper/AbstractFormDateSelect.php
> +        if (! $this->selectHelper instanceof FormSelect) {
```suggestion
        if (null === $this->selectHelper) {
```

2024-02-08 08:42 UTC, Slamdunk commented on src/View/Helper/FormMultiCheckbox.php
> +        if ($this->view && method_exists($this->view, 'plugin')) {
```suggestion
        if (null !== $this->view && method_exists($this->view, 'plugin')) {
```

2024-02-08 08:42 UTC, Slamdunk commented on src/View/Helper/FormSelect.php
> +        if ($this->view && method_exists($this->view, 'plugin')) {
```suggestion
        if (null !== $this->view && method_exists($this->view, 'plugin')) {
```

2024-02-08 08:42 UTC, Slamdunk commented on src/View/Helper/FormSelect.php
> +        if (! $this->formHiddenHelper instanceof FormHidden) {
```suggestion
        if (null === $this->formHiddenHelper) {
```

2024-02-19 07:08 UTC, Slamdunk approved these changes

2024-02-19 07:08 UTC, merged