doc:set select options
laminas/laminas-form pull request #74
Opened 2020-10-09 16:03 UTC by mushroot

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

- About the projects https://github.com/orgs/laminas/projects/8#card-36888172
this is my way to set value options from database for a select element

2020-10-09 16:27 UTC, froschdesign commented
@mushroot 
> this is my way to set value options from database for a select element

1. The description for application integration must contain only basic example. Everything else should be described separated. The plan is to create a "Cookbook" section like in [Mezzio](https://docs.mezzio.dev/mezzio/v3/cookbook/autowiring-routes-and-pipelines/).
2. In the controller is not the best idea because it means to duplicate code if the form is used multiple times. A [custom element](https://discourse.laminas.dev/t/handling-laminas-forms-with-dependencies-the-view-results/1343/12?u=froschdesign) can be used or the `Laminas\Db\Adapter\AdapterAwareTrait` and a delegator.

2020-10-09 16:29 UTC, froschdesign requested changes
The bugfix is good but everything else should be handled separately and therefore reverted. Thanks in advance!

2020-10-09 16:29 UTC, froschdesign commented on docs/book/application-integration/usage-in-a-laminas-mvc-application.md
> +            'type'    => Text::class,
Good catch! 👍

2020-10-09 17:08 UTC, mushroot commented on docs/book/application-integration/usage-in-a-laminas-mvc-application.md
> +            'type'    => Text::class,
ok, I reverted it.

2020-10-09 17:19 UTC, froschdesign approved these changes

2021-03-17 13:07 UTC, Slamdunk commented
Thank you

2021-03-17 13:07 UTC, merged